export interface Product {
  id: string;
  key: string; // për përkthim
  price: number;
  category: "Pizza" | "Pasta" | "Antipasti" | "Dolci" | "Bevande";
  image: string;
}

export const menuData: Product[] = [
  // ── ANTIPASTI ──────────────────────────────────────────────────────────────
  {
    id: "a1",
    key: "bruschetta",
    price: 2.9,
    category: "Antipasti",
    image: "images/frittura.png",
  },
  {
    id: "a2",
    key: "insalata-verde",
    price: 2.9,
    category: "Antipasti",
    image: "images/frittura.png",
  },
  {
    id: "a3",
    key: "insalata-rucola",
    price: 3.5,
    category: "Antipasti",
    image: "images/frittura.png",
  },
  {
    id: "a4",
    key: "insalata-caprese",
    price: 4.8,
    category: "Antipasti",
    image: "images/frittura.png",
  },

  // ── PASTA ──────────────────────────────────────────────────────────────────
  {
    id: "pa1",
    key: "spaghetti-aglio-olio",
    price: 4.9,
    category: "Pasta",
    image: "images/ragu.png",
  },
  {
    id: "pa2",
    key: "rigatoni-arrabiata",
    price: 5.5,
    category: "Pasta",
    image: "images/ragu.png",
  },
  {
    id: "pa3",
    key: "linguine-pesto",
    price: 5.9,
    category: "Pasta",
    image: "images/vongole.png",
  },
  {
    id: "pa4",
    key: "spaghetti-bolognese",
    price: 5.9,
    category: "Pasta",
    image: "images/ragu.png",
  },
  {
    id: "pa5",
    key: "tortellini-quattro-formaggi",
    price: 7.8,
    category: "Pasta",
    image: "images/ragu.png",
  },
  {
    id: "pa6",
    key: "lasagne-casa",
    price: 8.8,
    category: "Pasta",
    image: "images/ragu.png",
  },
  {
    id: "pa7",
    key: "linguine-scampi",
    price: 9.4,
    category: "Pasta",
    image: "images/vongole.png",
  },

  // ── PIZZA ──────────────────────────────────────────────────────────────────
  {
    id: "p1",
    key: "marinara",
    price: 5.5,
    category: "Pizza",
    image: "images/margherita.png",
  },
  {
    id: "p2",
    key: "margherita-classica",
    price: 6.5,
    category: "Pizza",
    image: "images/margherita.png",
  },
  {
    id: "p3",
    key: "funghi",
    price: 8.6,
    category: "Pizza",
    image: "images/margherita.png",
  },
  {
    id: "p4",
    key: "prosciutto-funghi",
    price: 8.9,
    category: "Pizza",
    image: "images/margherita.png",
  },
  {
    id: "p5",
    key: "diavola",
    price: 8.8,
    category: "Pizza",
    image: "images/diavola.png",
  },
  {
    id: "p6",
    key: "quattro-formaggi",
    price: 9.2,
    category: "Pizza",
    image: "images/margherita.png",
  },
  {
    id: "p7",
    key: "napoli",
    price: 9.6,
    category: "Pizza",
    image: "images/diavola.png",
  },
  {
    id: "p8",
    key: "tonno-cipolla",
    price: 9.6,
    category: "Pizza",
    image: "images/margherita.png",
  },
  {
    id: "p9",
    key: "primavera",
    price: 9.9,
    category: "Pizza",
    image: "images/margherita.png",
  },
  {
    id: "p10",
    key: "rucola",
    price: 9.9,
    category: "Pizza",
    image: "images/diavola.png",
  },
  {
    id: "p11",
    key: "capricciosa",
    price: 9.9,
    category: "Pizza",
    image: "images/diavola.png",
  },
  {
    id: "p12",
    key: "enrico",
    price: 9.9,
    category: "Pizza",
    image: "images/diavola.png",
  },
  {
    id: "p13",
    key: "tartufina",
    price: 11.9,
    category: "Pizza",
    image: "images/diavola.png",
  },
  {
    id: "p14",
    key: "burratina",
    price: 12.9,
    category: "Pizza",
    image: "images/margherita.png",
  },

  // ── DOLCI ──────────────────────────────────────────────────────────────────
  {
    id: "d1",
    key: "tiramisu",
    price: 2.9,
    category: "Dolci",
    image: "images/sfogliatella.png",
  },
  {
    id: "d2",
    key: "panna-cotta",
    price: 2.9,
    category: "Dolci",
    image: "images/sfogliatella.png",
  },

  // ── BEVANDE ────────────────────────────────────────────────────────────────
  // Soft Drinks
  {
    id: "b1",
    key: "coca-cola",
    price: 1.8,
    category: "Bevande",
    image: "images/fresh-pizza.png",
  },
  {
    id: "b2",
    key: "coca-cola-zero",
    price: 1.8,
    category: "Bevande",
    image: "images/fresh-pizza.png",
  },
  {
    id: "b3",
    key: "fanta",
    price: 1.8,
    category: "Bevande",
    image: "images/fresh-pizza.png",
  },
  {
    id: "b4",
    key: "sprite",
    price: 1.8,
    category: "Bevande",
    image: "images/fresh-pizza.png",
  },
  {
    id: "b5",
    key: "schweppes",
    price: 1.8,
    category: "Bevande",
    image: "images/fresh-pizza.png",
  },
  {
    id: "b6",
    key: "ice-tea",
    price: 1.8,
    category: "Bevande",
    image: "images/fresh-pizza.png",
  },
  {
    id: "b7",
    key: "juice",
    price: 1.8,
    category: "Bevande",
    image: "images/fresh-pizza.png",
  },
  // Water
  {
    id: "b8",
    key: "water-025",
    price: 1.0,
    category: "Bevande",
    image: "images/fresh-pizza.png",
  },
  {
    id: "b9",
    key: "water-075",
    price: 2.5,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b10",
    name: "Mineral Water",
    description: "0.25L",
    price: 1.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b11",
    name: "Mineral Water",
    description: "0.75L",
    price: 2.5,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  // Beers
  {
    id: "b12",
    name: "Peja Draught 0.3",
    description: "Draft beer 300ml",
    price: 2.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b13",
    name: "Peja Draught 0.5",
    description: "Draft beer 500ml",
    price: 3.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b14",
    name: "Heineken",
    description: "Bottle",
    price: 3.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b15",
    name: "Peja Bottle",
    description: "Bottle",
    price: 2.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b16",
    name: "Peroni Nastro Azzurro",
    description: "Bottle",
    price: 3.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b17",
    name: "Paulaner",
    description: "Bottle",
    price: 4.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b18",
    name: "Bavaria 0.0%",
    description: "Non-alcoholic beer",
    price: 2.5,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  // Wine by glass
  {
    id: "b19",
    name: "Vino Bianco",
    description: "Glass of white wine",
    price: 3.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b20",
    name: "Vino Rosso",
    description: "Glass of red wine",
    price: 3.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  // Wine bottles 0.187
  {
    id: "b21",
    name: "Stone Castle Chardonnay",
    description: "0.187L",
    price: 4.5,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b22",
    name: "Stone Castle Cabernet Sauvignon",
    description: "0.187L",
    price: 4.5,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b23",
    name: "Theranda Tramonto",
    description: "0.187L",
    price: 4.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b24",
    name: "Theranda Alba",
    description: "0.187L",
    price: 4.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  // Wine bottles 0.75
  {
    id: "b25",
    name: "Stone Castle Cabernet Sauvignon",
    description: "0.75L",
    price: 17.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b26",
    name: "Stone Castle Chardonnay",
    description: "0.75L",
    price: 18.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b27",
    name: "Theranda Cabernet Sauvignon",
    description: "0.75L",
    price: 20.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b28",
    name: "Pinot Grigio",
    description: "0.75L",
    price: 18.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b29",
    name: "Pinot Noir",
    description: "0.75L",
    price: 25.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b30",
    name: "Theranda Chardonnay",
    description: "0.75L",
    price: 25.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b31",
    name: "Hisari White",
    description: "0.75L",
    price: 35.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b32",
    name: "Hisari Red",
    description: "0.75L",
    price: 35.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b33",
    name: "Stone Riserva",
    description: "0.75L",
    price: 35.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b34",
    name: "She White",
    description: "0.75L",
    price: 60.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b35",
    name: "She Red",
    description: "0.75L",
    price: 65.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  // Aperitivo
  {
    id: "b36",
    name: "Campari Soda/Orange",
    description: "Aperitivo",
    price: 5.5,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b37",
    name: "Aperol Spritz",
    description: "Aperitivo",
    price: 5.5,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
];
