export interface Product {
  id: string;
  key: string; // për përkthim
  price: number;
  category: "Pizza" | "Pasta" | "Antipasti" | "Dolci" | "Bevande";
  image: string;
}

export const menuData: Product[] = [
  // ── ANTIPASTI ──────────────────────────────────────────────────────────────
  {
    id: "a1",
    key: "bruschetta",
    price: 2.9,
    category: "Antipasti",
    image: "images/frittura.png",
  },
  {
    id: "a2",
    key: "insalata-verde",
    price: 2.9,
    category: "Antipasti",
    image: "images/frittura.png",
  },
  {
    id: "a3",
    key: "insalata-rucola",
    price: 3.5,
    category: "Antipasti",
    image: "images/frittura.png",
  },
  {
    id: "a4",
    key: "insalata-caprese",
    price: 4.8,
    category: "Antipasti",
    image: "images/frittura.png",
  },

  // ── PASTA ──────────────────────────────────────────────────────────────────
  {
    id: "pa1",
    key: "spaghetti-aglio-olio",
    price: 4.9,
    category: "Pasta",
    image: "images/ragu.png",
  },
  {
    id: "pa2",
    key: "rigatoni-arrabiata",
    price: 5.5,
    category: "Pasta",
    image: "images/ragu.png",
  },
  {
    id: "pa3",
    key: "linguine-pesto",
    price: 5.9,
    category: "Pasta",
    image: "images/vongole.png",
  },
  {
    id: "pa4",
    key: "spaghetti-bolognese",
    price: 5.9,
    category: "Pasta",
    image: "images/ragu.png",
  },
  {
    id: "pa5",
    key: "tortellini-quattro-formaggi",
    price: 7.8,
    category: "Pasta",
    image: "images/ragu.png",
  },
  {
    id: "pa6",
    key: "lasagne-casa",
    price: 8.8,
    category: "Pasta",
    image: "images/ragu.png",
  },
  {
    id: "pa7",
    key: "linguine-scampi",
    price: 9.4,
    category: "Pasta",
    image: "images/vongole.png",
  },

  // ── PIZZA ──────────────────────────────────────────────────────────────────
  {
    id: "p1",
    key: "marinara",
    price: 5.5,
    category: "Pizza",
    image: "images/margherita.png",
  },
  {
    id: "p2",
    key: "margherita-classica",
    price: 6.5,
    category: "Pizza",
    image: "images/margherita.png",
  },
  {
    id: "p3",
    key: "funghi",
    price: 8.6,
    category: "Pizza",
    image: "images/margherita.png",
  },
  {
    id: "p4",
    key: "prosciutto-funghi",
    price: 8.9,
    category: "Pizza",
    image: "images/margherita.png",
  },
  {
    id: "p5",
    key: "diavola",
    price: 8.8,
    category: "Pizza",
    image: "images/diavola.png",
  },
  {
    id: "p6",
    key: "quattro-formaggi",
    price: 9.2,
    category: "Pizza",
    image: "images/margherita.png",
  },
  {
    id: "p7",
    key: "napoli",
    price: 9.6,
    category: "Pizza",
    image: "images/diavola.png",
  },
  {
    id: "p8",
    key: "tonno-cipolla",
    price: 9.6,
    category: "Pizza",
    image: "images/margherita.png",
  },
  {
    id: "p9",
    key: "primavera",
    price: 9.9,
    category: "Pizza",
    image: "images/margherita.png",
  },
  {
    id: "p10",
    key: "rucola",
    price: 9.9,
    category: "Pizza",
    image: "images/diavola.png",
  },
  {
    id: "p11",
    key: "capricciosa",
    price: 9.9,
    category: "Pizza",
    image: "images/diavola.png",
  },
  {
    id: "p12",
    key: "enrico",
    price: 9.9,
    category: "Pizza",
    image: "images/diavola.png",
  },
  {
    id: "p13",
    key: "tartufina",
    price: 11.9,
    category: "Pizza",
    image: "images/diavola.png",
  },
  {
    id: "p14",
    key: "burratina",
    price: 12.9,
    category: "Pizza",
    image: "images/margherita.png",
  },

  // ── DOLCI ──────────────────────────────────────────────────────────────────
  {
    id: "d1",
    key: "tiramisu",
    price: 2.9,
    category: "Dolci",
    image: "images/sfogliatella.png",
  },
  {
    id: "d2",
    key: "panna-cotta",
    price: 2.9,
    category: "Dolci",
    image: "images/sfogliatella.png",
  },

  // ── BEVANDE ────────────────────────────────────────────────────────────────
  // Soft Drinks
  {
    id: "b1",
    key: "coca-cola",
    price: 1.8,
    category: "Bevande",
    image: "images/fresh-pizza.png",
  },
  {
    id: "b2",
    key: "coca-cola-zero",
    price: 1.8,
    category: "Bevande",
    image: "images/fresh-pizza.png",
  },
  {
    id: "b3",
    key: "fanta",
    price: 1.8,
    category: "Bevande",
    image: "images/fresh-pizza.png",
  },
  {
    id: "b4",
    key: "sprite",
    price: 1.8,
    category: "Bevande",
    image: "images/fresh-pizza.png",
  },
  {
    id: "b5",
    key: "schweppes",
    price: 1.8,
    category: "Bevande",
    image: "images/fresh-pizza.png",
  },
  {
    id: "b6",
    key: "ice-tea",
    price: 1.8,
    category: "Bevande",
    image: "images/fresh-pizza.png",
  },
  {
    id: "b7",
    key: "juice",
    price: 1.8,
    category: "Bevande",
    image: "images/fresh-pizza.png",
  },
  // Water
  {
    id: "b8",
    key: "water-025",
    price: 1.0,
    category: "Bevande",
    image: "images/fresh-pizza.png",
  },
  {
    id: "b9",
    key: "water-075",
    price: 2.5,
    category: "Bevande",
    image: "images/fresh-pizza.png",
  },
  {
    id: "b10",
    key: "mineral-water-025",
    price: 1.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b11",
    key: "mineral-water-075",
    price: 2.5,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  // Beers
  {
    id: "b12",
    key: "peja-draught-03",
    price: 2.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b13",
    key: "peja-draught-05",
    price: 3.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b14",
    key: "heineken",
    price: 3.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b15",
    key: "peja-bottle",
    price: 2.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b16",
    key: "peroni-nastro-azzurro",
    price: 3.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b17",
    key: "paulaner",
    price: 4.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b18",
    key: "bavaria-00",
    price: 2.5,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  // Wine by glass
  {
    id: "b19",
    key: "vino-bianco",
    price: 3.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b20",
    key: "vino-rosso",
    price: 3.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  // Wine bottles 0.187
  {
    id: "b21",
    key: "stone-chardonnay-0187",
    price: 4.5,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b22",
    key: "stone-cabernet-0187",
    price: 4.5,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b23",
    key: "theranda-tramonto-0187",
    price: 4.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b24",
    key: "theranda-alba-0187",
    price: 4.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  // Wine bottles 0.75
  {
    id: "b25",
    key: "stone-cabernet-075",
    price: 17.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b26",
    key: "stone-chardonnay-075",
    price: 18.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b27",
    key: "theranda-cabernet-075",
    price: 20.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b28",
    key: "pinot-grigio-075",
    price: 18.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b29",
    key: "pinot-noir-075",
    price: 25.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b30",
    key: "theranda-chardonnay-075",
    price: 25.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b31",
    key: "hisari-white-075",
    price: 35.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b32",
    key: "hisari-red-075",
    price: 35.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b33",
    key: "stone-riserva-075",
    price: 35.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b34",
    key: "she-white-075",
    price: 60.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b35",
    key: "she-red-075",
    price: 65.0,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  // Aperitivo
  {
    id: "b36",
    key: "campari-soda-orange",
    price: 5.5,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
  {
    id: "b37",
    key: "aperol-spritz",
    price: 5.5,
    category: "Bevande",
    image: "/images/fresh-pizza.png",
  },
];
